name: clinica
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^1.6.14
  http: ^0.12.2
  http_parser: ^3.1.4
  dio: ^3.0.10
  pin_code_fields: ^4.0.0
  flutter_spinkit: ^4.1.2
  shared_preferences: ^0.5.8
  image_picker: ^0.6.7+7
  pie_chart: ^3.1.1
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.2
  sortedmap: ^0.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
